apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-infrastructure
  description: Terraform configuration for Azure VNet and Storage Account
  tags:
    - terraform
    - azure
spec:
  type: infrastructure
  owner: guests
  lifecycle: experimental
  providesApis:
    - terraform:azure:network/azurerm
  links:
    - url: https://github.com/Darcy-dev/backstage/main.tf
      title: Terraform Configuration (main.tf)
    - url: https://github.com/Darcy-dev/backstage/catalog-info.yaml
      title: Backstage Catalog Info
